
-- 1. 계정 생성 BLOCKINGUSR
CREATE USER BLOCKINGUSR IDENTIFIED BY BLOCKINGUSR;

-- 2. 권한 부여
GRANT CONNECT, RESOURCE, DBA TO BLOCKINGUSR;

-- RESOURCE : 개체 생성, 변경, 제거 권한
-- CONNECTION : DB 연결 권한
-- DBA : DB 관리자 권한

-- 3. 테이블 생성
CREATE TABLE BLOCK_TABLE (
    EXE_NO          NUMBER  NOT NULL PRIMARY KEY,
	EXE_NM          VARCHAR2(200),
	EXE_TYPE        VARCHAR2(50),
    EXE_DEL_YN      VARCHAR2(4),
	EXE_SAVE_DATE   DATE DEFAULT SYSDATE,
    EXE_SAVE_YN     VARCHAR2(4)
);

CREATE SEQUENCE BLOCK_SEQ START WITH 1 INCREMENT BY 1;

COMMENT ON TABLE BLOCK_TABLE IS '차단된 확장자 테이블';
COMMENT ON COLUMN BLOCK_TABLE.EXE_NO IS '확장자 순번';
COMMENT ON COLUMN BLOCK_TABLE.EXE_NM IS '확장자명';
COMMENT ON COLUMN BLOCK_TABLE.EXE_TYPE IS '확장자 종류';
COMMENT ON COLUMN BLOCK_TABLE.EXE_DEL_YN IS '삭제 여부 (Y: 삭제)';
COMMENT ON COLUMN BLOCK_TABLE.EXE_SAVE_DATE IS '저장 일시';
COMMENT ON COLUMN BLOCK_TABLE.EXE_SAVE_YN IS '저장여부';

ALTER TABLE BLOCK_TABLE
MODIFY EXE_SAVE_DATE DEFAULT SYSDATE;

COMMIT;